export default [
  {
    month: "4",
    num: 251,
    link: "",
    year: "2007",
    news: "",
    safe_title: "CD Tray Fight",
    transcript:
      "[[A stick figure is standing, holding a CD tray which is half-in his computer. There are other CDs on the floor.]]\nStick Figure: Hey. Hey! Stop retracting my CD!\n[[Label: I feel uncomfortable when my computer physically struggles with me. Sure, I can overpower it _now_, but it feels like a few short steps from here to the robot wars.]]\n{{alt text: This is silly, of course. The enemy will be born in the network.}}",
    alt: "This is silly, of course.  The enemy will be born in the network.",
    img: "https://imgs.xkcd.com/comics/cd_tray_fight.png",
    title: "CD Tray Fight",
    day: "20",
  },
  {
    month: "7",
    num: 133,
    link: "",
    year: "2006",
    news: "",
    safe_title: "The Raven",
    transcript:
      "[[A door opens, revealing Eminem wearing a hoodie]]\nNarration: Once upon a midnight dreary while I pondered, weak and weary, over many a quaint and curious volume of forgotten lore while i nodded, nearly napping, suddenly there came a tapping as if someone gently rapping rapping at my chamber door...\n<<click>>\n<<creak>>\nEminem: Yo.\n{{title text: Yes, Eminem is wearing a sleeveless hoodie. What of it?}}",
    alt: "Yes, Eminem is wearing a sleeveless hoodie.  What of it?",
    img: "https://imgs.xkcd.com/comics/the_raven.jpg",
    title: "The Raven",
    day: "26",
  },
  {
    month: "1",
    num: 1158,
    link: "",
    year: "2013",
    news: "",
    safe_title: "Rubber Sheet",
    transcript:
      "[[A woman is standing on the left edge of a rubber sheet. In the middle is a bowling ball. A man in a beret is standing on top of the bowling ball.]]\nBeret guy: Imagine a giant bowling ball on a rubber sheet. The ball's weight makes a dent in the sheet. \n\n[[A rope has been attached to the sheet, and is pulling downwards. The woman peers down.]]\nBeret guy: Now imagine a rope that pulls the ball down even further. ...Annnnd...\n\n[[The rope snaps. The woman loses her balance as the sheet shakes and the ball flies into the air.]]\nBOOOIING\nBeret guy: Wheee\n\n[[The woman stands on the now stable sheet. The ball falls down towards it.]]\nWoman: ... Oh. I thought this was about physics. \nBeret guy: Imagining is fun! \n\n{{Title text: It IS about physics. It ALL is.}}",
    alt: "It IS about physics. It ALL is.",
    img: "https://imgs.xkcd.com/comics/rubber_sheet.png",
    title: "Rubber Sheet",
    day: "9",
  },
  {
    month: "1",
    num: 691,
    link: "",
    year: "2010",
    news: "",
    safe_title: "MicroSD",
    transcript:
      "[[Two figures approach a table]]\nFigure 1: Hey, what's up?\nFigure 2: Shhhhh.\nFigure 1: Hrm?\nFigure 2: There's a microSD card on your table.\n\n[[A microSD card sits next to an assortment of coins for size reference.]]\nFigure 1 (out of panel): So?\nFigure 2 (out of panel): I dunno, high storage densities freak me out. A whole aisle of library shelves on something smaller than a dime.\n\n[[The two figures stand near the table, the second figure peering at the coins and card on the table.]]\nFigure 2: Libraries are unnerving enough--millions of ideas surrounding you, towering over you. These cards fill me with that same reverence, that same intimidation.\n\n[[The first figure stands alone]]\nFigure 2 (out of panel): ...that same faint arousal. Maybe I'll just touch it.\nFigure 1: If you lose that card I'm _NOT_ helping you find it.\n\n{{Title text: That card holds a refrigerator carton's worth of floppy discs, and a soda can full of those cards could hold the entire iTunes store's music library. Mmmm.}}",
    alt: "That card holds a refrigerator carton's worth of floppy discs, and a soda can full of those cards could hold the entire iTunes store's music library. Mmmm.",
    img: "https://imgs.xkcd.com/comics/microsd.png",
    title: "MicroSD",
    day: "20",
  },
  {
    month: "12",
    num: 1150,
    link: "",
    year: "2012",
    news: "",
    safe_title: "Instagram",
    transcript:
      "[[One man sits at a computer. Another stands behind him, talking.]]\nMan #2: I've been putting all my stuff in Chad's Garage. He has nice shelves. And he lets me in to see it whenever I want. \n\n[[We see a handwritten note.]]\nMan #2: But I just got this note from him:\nNote: Dude, in like a month im gonna Craigslist all that shit you left in my garage. Just FYI. -- Chad\n\n[[A close-up of man #2.]]\nMan #2: It's an *outrage*! This is no way to run a storage business! \nMan #1: Are you paying him to look after your stuff? \n\n[[We see both characters again, as in panel #1.]]\nMan #2: No.\nMan #1: Then what he runs isn't a storage business.\nMan #2: Well, I'm *this* close to not giving him any more stuff. \nMan #1: That'll teach him. \n\n{{Title text: I'm gonna call the cops and get Chad arrested for theft, then move all my stuff to the house across the street. Hopefully the owners there are more responsible.}}",
    alt: "I'm gonna call the cops and get Chad arrested for theft, then move all my stuff to the house across the street. Hopefully the owners there are more responsible.",
    img: "https://imgs.xkcd.com/comics/instagram.png",
    title: "Instagram",
    day: "21",
  },
  {
    month: "11",
    num: 1754,
    link: "",
    year: "2016",
    news: "",
    safe_title: "Tornado Safety Tips",
    transcript: "",
    alt: "It's a myth that you can never cross mountains safely, but be sure you understand how the climatic situation there will affect your parent thunderstorm.",
    img: "https://imgs.xkcd.com/comics/tornado_safety_tips.png",
    title: "Tornado Safety Tips",
    day: "2",
  },
  {
    month: "1",
    num: 2253,
    link: "",
    year: "2020",
    news: "",
    safe_title: "Star Wars Voyager 1",
    transcript: "",
    alt: "There's some flexibility depending on your standards for measuring runtime and the various special editions. If you still want to have a party, I'm sure you can find some combination that works.",
    img: "https://imgs.xkcd.com/comics/star_wars_voyager_1.png",
    title: "Star Wars Voyager 1",
    day: "10",
  },
  {
    month: "5",
    num: 1059,
    link: "",
    year: "2012",
    news: "",
    safe_title: "Bel-Air",
    transcript:
      "[[A man sits on an easy chair in front of a TV.]]\nTV: Well, my posh Bel Air life took a turn for the worse.\n\n[[Same scene.]]\nTV: It's a story best related in a doggerel verse.\n\n[[Same scene.]]\nTV: So kick back, relax, lemme put on some Adele for ya,\n\n[[Man raises the remote and points at the screen.]]\nTV: While I tell you why I'm running for mayor of Phila--\n<<CLICK>>\n\n{{Title text: Aaron Sorkin has been tapped to write the TV movie about the aging prince's eventual election to Pat Toomey's Senate seat, currently titled either 'FRESHman Senator' or 'Mr. Smith Goes to Washington'.}}",
    alt: "Aaron Sorkin has been tapped to write the TV movie about the aging prince's eventual election to Pat Toomey's Senate seat, currently titled either 'FRESHman Senator' or 'Mr. Smith Goes to Washington'.",
    img: "https://imgs.xkcd.com/comics/bel_air.png",
    title: "Bel-Air",
    day: "23",
  },
  {
    month: "2",
    num: 1647,
    link: "",
    year: "2016",
    news: "",
    safe_title: "Diacritics",
    transcript:
      "[[A lot of people making toasts]]\n\nJust a regular fucking person: Champagne for my real friends and real pain for my sham friends!\n\nA biologist: Pseudopods for my real friends and real pods for my pseudo-friends!\n\nAn anachronist: Petticoats for my real friends and real coats for my petty friends.\n\nA botanist: Loosestrife for my real friends and real strife for my loose friends!\n\nAn entomologist: Ladybugs for my real friends and real bugs for my lady friends!\n\nSome kind of insufferable 90s nerd: Single-payer for my real friends and realplayer for my single friends.\n\nInternet addict: Tumbleweeds for my real friends and real weed for my tumblr friends!\n\nBird lord: Fauxhawks for my real friends and real hawks for my faux friends!\n\n{{Title text: Platonic solids for my real friends and real solids for my platonic friends!}}",
    alt: "Using diacritics correctly is not my forté.",
    img: "https://imgs.xkcd.com/comics/diacritics.png",
    title: "Diacritics",
    day: "24",
  },
  {
    month: "2",
    num: 2265,
    link: "",
    year: "2020",
    news: "",
    safe_title: "Tax AI",
    transcript: "",
    alt: "I ended up getting my tax return prepared at a local place by a really friendly pretrained neural net named Greg.",
    img: "https://imgs.xkcd.com/comics/tax_ai.png",
    title: "Tax AI",
    day: "7",
  },
];
