name: Vercel Deploy and Test
env: ${{ secrets.VERCEL_TOKEN }}
on:
  push:
    branches:
      - main 

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.2.0 

    - name: Install Dependencies
      run: npm install

    - name: Run Integration Tests
      run: npm run test:integration

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
